{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "webrtc",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-2.4.0.aar",
          "url": "webrtc-2.4.0.aar",
          "size": 86487,
          "sha512": "f69194f8bdc225b057f6d107f2b2c0f37b99a76ce2f068b1054c7c3ee2c8c82450ccd63b79d795ebaad69efe64320f83bbe2fc0b3980716aa17ba04f522ceda8",
          "sha256": "7e195d110cee8a1997515660d1820ffc02179e606225fef57e9aa2be3c5771cf",
          "sha1": "4f268058730477c8f1969d27b9839efcba5ea733",
          "md5": "559797139bd7fd37f7ac0b8536c2eb05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "AppRTCMobile",
          "module": "libwebrtc",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-2.4.0.aar",
          "url": "webrtc-2.4.0.aar",
          "size": 86487,
          "sha512": "f69194f8bdc225b057f6d107f2b2c0f37b99a76ce2f068b1054c7c3ee2c8c82450ccd63b79d795ebaad69efe64320f83bbe2fc0b3980716aa17ba04f522ceda8",
          "sha256": "7e195d110cee8a1997515660d1820ffc02179e606225fef57e9aa2be3c5771cf",
          "sha1": "4f268058730477c8f1969d27b9839efcba5ea733",
          "md5": "559797139bd7fd37f7ac0b8536c2eb05"
        }
      ]
    }
  ]
}
