{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "webrtc",
    "version": "2.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-2.3.1.aar",
          "url": "webrtc-2.3.1.aar",
          "size": 77534,
          "sha512": "50522b42609756f6697141d5ee23bb7d507f442f52b1ded077fee9ba9214154f655faac74992b9e556cc1e276939e55325412966e5e7ad805e6a2f6f0e59fb1d",
          "sha256": "ca2f99a2349d8d3a2db2e68fc09db03b684e6f5a48b4a6d62c01709308ffb048",
          "sha1": "dee0cb8be23bc94f726548030cddd88d342f610f",
          "md5": "e63807841da8d762c3b55fe854b4a7cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.3.0"
          }
        },
        {
          "group": "AppRTCMobile",
          "module": "libwebrtc",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-2.3.1.aar",
          "url": "webrtc-2.3.1.aar",
          "size": 77534,
          "sha512": "50522b42609756f6697141d5ee23bb7d507f442f52b1ded077fee9ba9214154f655faac74992b9e556cc1e276939e55325412966e5e7ad805e6a2f6f0e59fb1d",
          "sha256": "ca2f99a2349d8d3a2db2e68fc09db03b684e6f5a48b4a6d62c01709308ffb048",
          "sha1": "dee0cb8be23bc94f726548030cddd88d342f610f",
          "md5": "e63807841da8d762c3b55fe854b4a7cc"
        }
      ]
    }
  ]
}
