{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "webrtc",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-2.2.0.aar",
          "url": "webrtc-2.2.0.aar",
          "size": 77364,
          "sha512": "a2061ce65576c6b62b0f8d7073d64b9cb06ee9a5d05ba4481be998d607f67d713b3e11ae11b0aee2cd19aecfefbfffbd170622dd6c1347f772b06223b509b6df",
          "sha256": "6820f48372b255f72a180e74732ca87075f3b9489c26229fc18473a4b224ea8c",
          "sha1": "6ffe4dd80437421f582f6cac90033bacdc861cd8",
          "md5": "cbd867c257e48217df6fdeaac93bd5e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.webrtc",
          "module": "google-webrtc",
          "version": {
            "requires": "1.0.32006"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "webrtc-2.2.0.aar",
          "url": "webrtc-2.2.0.aar",
          "size": 77364,
          "sha512": "a2061ce65576c6b62b0f8d7073d64b9cb06ee9a5d05ba4481be998d607f67d713b3e11ae11b0aee2cd19aecfefbfffbd170622dd6c1347f772b06223b509b6df",
          "sha256": "6820f48372b255f72a180e74732ca87075f3b9489c26229fc18473a4b224ea8c",
          "sha1": "6ffe4dd80437421f582f6cac90033bacdc861cd8",
          "md5": "cbd867c257e48217df6fdeaac93bd5e4"
        }
      ]
    }
  ]
}
